### ISSUE TITLE
Retroarch support

### ISSUE THREAD

**Issue by walllable** [n1ckoates/steamdeck-emulation#16]
Hey, figured I'd open an issue up for flatpak Retroarch since I've got it set up - Specifically I got it set up for the mGBA and snes9x cores, but it should be pretty universal - You just need to change the Steam category name, and the core in the command line argument. Feel free to edit this for the guide of course, I imagine just copying and pasting this won't be fully up to snuff for a guide.

---

First of all, if you're storing your ROMs on an SD card, you'll have to override flatpak's permissions for Retroarch so it can access the SD card (Or, more specifically, the folder that the SD card is mounted in.)
Install Retroarch from Discovery if you haven't already, then go ahead and open up a terminal (start menu/lower-right Deck logo, system, Konsole - Don't worry, we're only entering two commands!) In the terminal, enter `passwd` to set a password for the current user account (deck). Then, enter `sudo flatpak override org.libretro.RetroArch --filesystem=/run/media/` and type in the password you just set.

I won't be covering setting up Retroarch itself here (setting the default path for where you keep your ROMs, adding cores, etc), frankly I'm too lazy.

Now for setting up Steam ROM Emulator. Open it up, and click on "Parsers". Click the "Community Presets" text box, and a list of presets should appear, most of them for Retroarch. Choose the one that applies to the core you want to set up. I'll be choosing snes9x in my example, but it should be fairly universal, as I'll show later on (these set up a decent amount of the field for you.) Scroll down to the bottom, and click on "Enable advanced options," then scroll back up near the top, and untick "Append arguments to executable."
Now for the text you'll be putting in to each field:
- Under "Executable," enter `/usr/bin/flatpak`
- Under "Executable modifier," enter `/usr/bin/flatpak run org.libretro.RetroArch` (I put `/usr/bin/flatpak` in here again because someone mentioned running into some sort of issue related to this when setting up Dolphin - see [here](https://discord.com/channels/865611969661632521/865685603223994419/950186808216543293) on the Steam Deck discord)
- Under "ROMs directory," put where you've stored your roms - In my case, since they're on my SD card, my path is `/run/media/Deck/roms/snes`

And that should be pretty much it, from what I can tell. Let me know if you run into any issues while testing this.

**Comment by walllable** [comment]
Found this, but not sure how to use this with SRM... https://steamcommunity.com/sharedfiles/filedetails/?id=2601830633

**Comment by nchristopher** [comment]
I don't see why the Steam version of Retroarch would behave differently than the Flatpak one. This can definitely be done.
