### ISSUE TITLE
🎮 SNES guide (bsnes)

### ISSUE THREAD

**Issue by any1th3r3** [n1ckoates/steamdeck-emulation#23]
bsnes is usually recommended, instead of snes9x, for higher-end systems since it is cycle accurate (see [Emu Gen wiki](https://emulation.gametechwiki.com/index.php/Super_Nintendo_emulators)), so it might make sense to have a guide for it (instead / as well?).

**Comment by nchristopher** [comment]
I was already planning to have multiple emulator guides per system, so while I'm not as experienced with bsnes, I'll definitely look into it.

**Comment by sli** [comment]
The setup is fairly straightforward. The package name is `dev.bsnes.bsnes` and it needs the `--fullscreen` flag supplied in the run command, and of course needs the joypad bindings configured.
